// lib/content/season1.ts

export const season1 = {
  name: "UR Temporada 1",
  subtitle: "Territórios em Disputa",
  slogan: "Entre na temporada. Evolua no seu ritmo.",
  message: "Cada presença conta. Cada jogo constrói histórico. Cada atleta tem um caminho.",
  poles: [
    {
      id: "bh",
      name: "Belo Horizonte",
      short: "BH",
      shieldPath: "/season-1/poles/pole-bh.svg",
      activeTeams: 8,
      totalPoints: 0,
      status: "Polo Ativo",
    },
    {
      id: "betim",
      name: "Betim",
      short: "Betim",
      shieldPath: "/season-1/poles/pole-betim.svg",
      activeTeams: 5,
      totalPoints: 0,
      status: "Polo Ativo",
    },
    {
      id: "contagem",
      name: "Contagem",
      short: "Contagem",
      shieldPath: "/season-1/poles/pole-contagem.svg",
      activeTeams: 4,
      totalPoints: 0,
      status: "Polo Ativo",
    },
  ] as const,
  ladder: [
    {
      id: "ur-play",
      name: "UR Play",
      description: "Entrada, observação e nivelamento. O primeiro passo para jogar e formar histórico.",
      symbolSolid: "/season-1/symbols/ur-play-solid.svg",
      symbolLine: "/season-1/symbols/ur-play-line.svg",
      symbolBadge: "/season-1/symbols/ur-play-badge.svg",
      symbolMobile: "/season-1/symbols/ur-play-mobile.svg",
      href: "/ur-play",
      cta: "Entrar pelo UR Play",
      color: "#D4A437",
    },
    {
      id: "ur-sprint",
      name: "UR Sprint",
      description: "Primeiras disputas organizadas para ganhar ritmo, somar pontos e entender seu nível.",
      symbolSolid: "/season-1/symbols/ur-sprint-solid.svg",
      symbolLine: "/season-1/symbols/ur-sprint-line.svg",
      symbolBadge: "/season-1/symbols/ur-sprint-badge.svg",
      symbolMobile: "/season-1/symbols/ur-sprint-mobile.svg",
      href: "/eventos",
      cta: "Ver UR Sprint",
      color: "#D4A437",
    },
    {
      id: "ur-series",
      name: "UR Series",
      description: "Etapas maiores da temporada, com mais mídia e maior impacto no ranking.",
      symbolSolid: "/season-1/symbols/ur-series-solid.svg",
      symbolLine: "/season-1/symbols/ur-series-line.svg",
      symbolBadge: "/season-1/symbols/ur-series-badge.svg",
      symbolMobile: "/season-1/symbols/ur-series-mobile.svg",
      href: "/eventos",
      cta: "Ver UR Series",
      color: "#D4A437",
    },
    {
      id: "ur-legends",
      name: "UR Legends",
      description: "Fechamento do ciclo para atletas, equipes e polos em destaque dentro da temporada.",
      symbolSolid: "/season-1/symbols/ur-legends-solid.svg",
      symbolLine: "/season-1/symbols/ur-legends-line.svg",
      symbolBadge: "/season-1/symbols/ur-legends-badge.svg",
      symbolMobile: "/season-1/symbols/ur-legends-mobile.svg",
      href: "/eventos",
      cta: "Ver UR Legends",
      color: "#D4A437",
    },
  ] as const,
  modalities: [
    { id: "quartetos", name: "Quartetos", symbolSolid: "/season-1/symbols/quartetos-solid.svg", symbolLine: "/season-1/symbols/quartetos-line.svg" },
    { id: "duplas-m", name: "Duplas Masculinas", symbolSolid: "/season-1/symbols/duplas-m-solid.svg", symbolLine: "/season-1/symbols/duplas-m-line.svg" },
    { id: "duplas-f", name: "Duplas Femininas", symbolSolid: "/season-1/symbols/duplas-f-solid.svg", symbolLine: "/season-1/symbols/duplas-f-line.svg" },
    { id: "duplas-mistas", name: "Duplas Mistas", symbolSolid: "/season-1/symbols/duplas-mistas-solid.svg", symbolLine: "/season-1/symbols/duplas-mistas-line.svg" },
  ] as const,
  mockRankings: [
    { rank: 1, name: "Atleta #1", pole: "BH", level: "N1", points: 0, variation: 0 },
    { rank: 2, name: "Atleta #2", pole: "Betim", level: "N1", points: 0, variation: 0 },
    { rank: 3, name: "Atleta #3", pole: "Contagem", level: "N2", points: 0, variation: 0 },
    { rank: 4, name: "Atleta #4", pole: "BH", level: "N2", points: 0, variation: 0 },
    { rank: 5, name: "Atleta #5", pole: "Betim", level: "N3", points: 0, variation: 0 },
  ] as const,
  mockBracket: {
    stage: "sprint" as const,
    quarterfinals: [
      { id: "qf1", a: "Atleta A", b: "Atleta B", winner: null },
      { id: "qf2", a: "Atleta C", b: "Atleta D", winner: null },
      { id: "qf3", a: "Atleta E", b: "Atleta F", winner: null },
      { id: "qf4", a: "Atleta G", b: "Atleta H", winner: null },
    ],
    semifinals: [
      { id: "sf1", a: "—", b: "—", winner: null },
      { id: "sf2", a: "—", b: "—", winner: null },
    ],
    final: { id: "final", a: "—", b: "—", winner: null },
  },
};
